//
// BudgetAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class BudgetAPI {
    /**

     - parameter _id: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func deleteBudget(_id: Int, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        deleteBudgetWithRequestBuilder(_id: _id).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - DELETE /v1/Budget/{id}
     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     
     - parameter _id: (path)  

     - returns: RequestBuilder<Void> 
     */
    open class func deleteBudgetWithRequestBuilder(_id: Int) -> RequestBuilder<Void> {
        var path = "/v1/Budget/{id}"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getBudgets(completion: @escaping ((_ data: GetUserBudgetResponse?,_ error: Error?) -> Void)) {
        getBudgetsWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /v1/Budget
     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     - examples: [{contentType=application/json, example={
  "overallActualSpending" : 6.027456183070403,
  "overallSpendingBudget" : 0.8008281904610115,
  "userBudgets" : [ {
    "cheqCategoryTitle" : "cheqCategoryTitle",
    "categoryIconUrl" : "categoryIconUrl",
    "spendingBudget" : 5.962133916683182,
    "canDelete" : true,
    "id" : 1,
    "actualSpending" : 5.637376656633329
  }, {
    "cheqCategoryTitle" : "cheqCategoryTitle",
    "categoryIconUrl" : "categoryIconUrl",
    "spendingBudget" : 5.962133916683182,
    "canDelete" : true,
    "id" : 1,
    "actualSpending" : 5.637376656633329
  } ]
}}]

     - returns: RequestBuilder<GetUserBudgetResponse> 
     */
    open class func getBudgetsWithRequestBuilder() -> RequestBuilder<GetUserBudgetResponse> {
        let path = "/v1/Budget"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<GetUserBudgetResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**

     - parameter _id: (path)  
     - parameter request: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func updateUserBudget(_id: Int, request: PutSpendingBudgetRequest? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        updateUserBudgetWithRequestBuilder(_id: _id, request: request).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - PUT /v1/Budget/{id}
     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     
     - parameter _id: (path)  
     - parameter request: (body)  (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func updateUserBudgetWithRequestBuilder(_id: Int, request: PutSpendingBudgetRequest? = nil) -> RequestBuilder<Void> {
        var path = "/v1/Budget/{id}"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: request)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

}
