//
// SpendingAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class SpendingAPI {
    /**

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getCurrentMonthSpending(completion: @escaping ((_ data: GetMonthSpendingsResponse?,_ error: Error?) -> Void)) {
        getCurrentMonthSpendingWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /v1/Spending/month
     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     - examples: [{contentType=application/json, example={
  "totalIncome" : 1.4658129805029452,
  "totalSpend" : 6.027456183070403,
  "accountName" : "accountName",
  "accountType" : "accountType",
  "categoryStats" : [ {
    "sum" : 2.3021358869347655,
    "category" : "category",
    "numberOfTransactions" : 5
  }, {
    "sum" : 2.3021358869347655,
    "category" : "category",
    "numberOfTransactions" : 5
  } ],
  "accountNumber" : "accountNumber",
  "accountBalance" : 0.8008281904610115,
  "dailySpending" : [ {
    "date" : "date",
    "spending" : [ {
      "merchant" : "merchant",
      "sum" : 5.962133916683182,
      "transactedAt" : "transactedAt",
      "merchantLogoUrl" : "merchantLogoUrl",
      "category" : "category",
      "info" : "info"
    }, {
      "merchant" : "merchant",
      "sum" : 5.962133916683182,
      "transactedAt" : "transactedAt",
      "merchantLogoUrl" : "merchantLogoUrl",
      "category" : "category",
      "info" : "info"
    } ]
  }, {
    "date" : "date",
    "spending" : [ {
      "merchant" : "merchant",
      "sum" : 5.962133916683182,
      "transactedAt" : "transactedAt",
      "merchantLogoUrl" : "merchantLogoUrl",
      "category" : "category",
      "info" : "info"
    }, {
      "merchant" : "merchant",
      "sum" : 5.962133916683182,
      "transactedAt" : "transactedAt",
      "merchantLogoUrl" : "merchantLogoUrl",
      "category" : "category",
      "info" : "info"
    } ]
  } ],
  "assetType" : "assetType"
}}]

     - returns: RequestBuilder<GetMonthSpendingsResponse> 
     */
    open class func getCurrentMonthSpendingWithRequestBuilder() -> RequestBuilder<GetMonthSpendingsResponse> {
        let path = "/v1/Spending/month"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<GetMonthSpendingsResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getCurrentWeekSpending(completion: @escaping ((_ data: GetWeekSpendingsResponse?,_ error: Error?) -> Void)) {
        getCurrentWeekSpendingWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /v1/Spending/week
     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     - examples: [{contentType=application/json, example={
  "totalIncome" : 1.4658129805029452,
  "totalSpend" : 6.027456183070403,
  "accountName" : "accountName",
  "accountType" : "accountType",
  "categoryStats" : [ {
    "sum" : 2.3021358869347655,
    "category" : "category",
    "numberOfTransactions" : 5
  }, {
    "sum" : 2.3021358869347655,
    "category" : "category",
    "numberOfTransactions" : 5
  } ],
  "accountNumber" : "accountNumber",
  "accountBalance" : 0.8008281904610115,
  "dailySpending" : [ {
    "date" : "date",
    "spending" : [ {
      "merchant" : "merchant",
      "sum" : 5.962133916683182,
      "transactedAt" : "transactedAt",
      "merchantLogoUrl" : "merchantLogoUrl",
      "category" : "category",
      "info" : "info"
    }, {
      "merchant" : "merchant",
      "sum" : 5.962133916683182,
      "transactedAt" : "transactedAt",
      "merchantLogoUrl" : "merchantLogoUrl",
      "category" : "category",
      "info" : "info"
    } ]
  }, {
    "date" : "date",
    "spending" : [ {
      "merchant" : "merchant",
      "sum" : 5.962133916683182,
      "transactedAt" : "transactedAt",
      "merchantLogoUrl" : "merchantLogoUrl",
      "category" : "category",
      "info" : "info"
    }, {
      "merchant" : "merchant",
      "sum" : 5.962133916683182,
      "transactedAt" : "transactedAt",
      "merchantLogoUrl" : "merchantLogoUrl",
      "category" : "category",
      "info" : "info"
    } ]
  } ],
  "assetType" : "assetType"
}}]

     - returns: RequestBuilder<GetWeekSpendingsResponse> 
     */
    open class func getCurrentWeekSpendingWithRequestBuilder() -> RequestBuilder<GetWeekSpendingsResponse> {
        let path = "/v1/Spending/week"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<GetWeekSpendingsResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getTodaySpending(completion: @escaping ((_ data: GetTodaySpendingResponse?,_ error: Error?) -> Void)) {
        getTodaySpendingWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /v1/Spending/today
     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     - examples: [{contentType=application/json, example={
  "totalIncome" : 1.4658129805029452,
  "totalSpend" : 6.027456183070403,
  "spending" : [ {
    "merchant" : "merchant",
    "sum" : 5.962133916683182,
    "transactedAt" : "transactedAt",
    "merchantLogoUrl" : "merchantLogoUrl",
    "category" : "category",
    "info" : "info"
  }, {
    "merchant" : "merchant",
    "sum" : 5.962133916683182,
    "transactedAt" : "transactedAt",
    "merchantLogoUrl" : "merchantLogoUrl",
    "category" : "category",
    "info" : "info"
  } ],
  "accountName" : "accountName",
  "accountType" : "accountType",
  "categoryStats" : [ {
    "sum" : 2.3021358869347655,
    "category" : "category",
    "numberOfTransactions" : 5
  }, {
    "sum" : 2.3021358869347655,
    "category" : "category",
    "numberOfTransactions" : 5
  } ],
  "accountNumber" : "accountNumber",
  "accountBalance" : 0.8008281904610115,
  "assetType" : "assetType"
}}]

     - returns: RequestBuilder<GetTodaySpendingResponse> 
     */
    open class func getTodaySpendingWithRequestBuilder() -> RequestBuilder<GetTodaySpendingResponse> {
        let path = "/v1/Spending/today"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<GetTodaySpendingResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
