//
// BorrowOverview.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BorrowOverview: Codable {

    public var availableWithdrawAmount: Double?
    public var nextPayDay: String?
    public var pendingRepayments: [LoanTransaction]?
    public var histories: [LoanTransaction]?

    public init(availableWithdrawAmount: Double?, nextPayDay: String?, pendingRepayments: [LoanTransaction]?, histories: [LoanTransaction]?) {
        self.availableWithdrawAmount = availableWithdrawAmount
        self.nextPayDay = nextPayDay
        self.pendingRepayments = pendingRepayments
        self.histories = histories
    }


}

