//
// BorrowOverview.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BorrowOverview: Codable {

    public var availableCashoutAmount: Double?
    public var canUploadTimesheet: Bool?
    public var activities: [LoanActivity]?

    public init(availableCashoutAmount: Double?, canUploadTimesheet: Bool?, activities: [LoanActivity]?) {
        self.availableCashoutAmount = availableCashoutAmount
        self.canUploadTimesheet = canUploadTimesheet
        self.activities = activities
    }


}

