//
// DeclineDetail.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DeclineDetail: Codable {

    public var declineReason: String?
    public var declineDescription: String?

    public init(declineReason: String?, declineDescription: String?) {
        self.declineReason = declineReason
        self.declineDescription = declineDescription
    }


}

