//
// DeclineDetail.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DeclineDetail: Codable {

    public enum DeclineReason: String, Codable { 
        case _none = "None"
        case creditAssessment = "CreditAssessment"
        case employmentType = "EmploymentType"
        case jointAccount = "JointAccount"
        case monthlyPayCycle = "MonthlyPayCycle"
        case hasWriteOff = "HasWriteOff"
        case hasOverdueLoans = "HasOverdueLoans"
        case identityConflict = "IdentityConflict"
        case reachedCapacity = "ReachedCapacity"
        case salaryInDifferentBank = "SalaryInDifferentBank"
        case noEnoughSalaryInfo = "NoEnoughSalaryInfo"
        case selectYourSalary = "SelectYourSalary"
        case payCycleStopped = "PayCycleStopped"
    }
    public var declineReason: DeclineReason?
    public var declineTitle: String?
    public var declineDescription: String?
    public var learnMoreLink: String?

    public init(declineReason: DeclineReason?, declineTitle: String?, declineDescription: String?, learnMoreLink: String?) {
        self.declineReason = declineReason
        self.declineTitle = declineTitle
        self.declineDescription = declineDescription
        self.learnMoreLink = learnMoreLink
    }
}

