//
// EligibleRequirement.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct EligibleRequirement: Codable {

    public enum KycStatus: String, Codable { 
        case blocked = "Blocked"
        case notStarted = "NotStarted"
        case createdApplicant = "CreatedApplicant"
        case inProcessing = "InProcessing"
        case failed = "Failed"
        case success = "Success"
    }
    public enum ProofOfAddressStatus: String, Codable { 
        case _required = "Required"
        case success = "Success"
        case failed = "Failed"
    }
    public var hasEmploymentDetail: Bool?
    public var hasPayCycle: Bool?
    public var isReviewingPayCycle: Bool?
    public var hasProofOfProductivity: Bool?
    public var userAction: UserAction?
    public var hasBankAccountDetail: Bool?
    public var kycStatus: KycStatus?
    public var proofOfAddressStatus: ProofOfAddressStatus?

    public init(hasEmploymentDetail: Bool?, hasPayCycle: Bool?, isReviewingPayCycle: Bool?, hasProofOfProductivity: Bool?, userAction: UserAction?, hasBankAccountDetail: Bool?, kycStatus: KycStatus?, proofOfAddressStatus: ProofOfAddressStatus?) {
        self.hasEmploymentDetail = hasEmploymentDetail
        self.hasPayCycle = hasPayCycle
        self.isReviewingPayCycle = isReviewingPayCycle
        self.hasProofOfProductivity = hasProofOfProductivity
        self.userAction = userAction
        self.hasBankAccountDetail = hasBankAccountDetail
        self.kycStatus = kycStatus
        self.proofOfAddressStatus = proofOfAddressStatus
    }

}

