//
// EligibleRequirement.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct EligibleRequirement: Codable {

    public var hasEmploymentDetail: Bool?
    public var hasDirectDebitDetail: Bool?
    public var kycStatus: String?

    public init(hasEmploymentDetail: Bool?, hasDirectDebitDetail: Bool?, kycStatus: String?) {
        self.hasEmploymentDetail = hasEmploymentDetail
        self.hasDirectDebitDetail = hasDirectDebitDetail
        self.kycStatus = kycStatus
    }


}

