//
// EligibilityFailureDetail.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct EligibilityFailureDetail: Codable {

    public enum FailureReason: String, Codable { 
        case creditAssessment = "CreditAssessment"
        case directDebit = "DirectDebit"
        case employmentType = "EmploymentType"
        case jointAccount = "JointAccount"
        case kyc = "Kyc"
        case monthlyPayCycle = "MonthlyPayCycle"
        case nameConflict = "NameConflict"
        case notWorkEnough = "NotWorkEnough"
        case notRepayLoan = "NotRepayLoan"
        case noPayCycle = "NoPayCycle"
    }
    public var failureReason: FailureReason?
    public var failureReasonDescription: String?

    public init(failureReason: FailureReason?, failureReasonDescription: String?) {
        self.failureReason = failureReason
        self.failureReasonDescription = failureReasonDescription
    }


}

