//
// EligibleRequirement.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct EligibleRequirement: Codable {

    public enum KycStatus: String, Codable { 
        case blocked = "Blocked"
        case notStarted = "NotStarted"
        case createdApplicant = "CreatedApplicant"
        case inProcessing = "InProcessing"
        case failed = "Failed"
        case success = "Success"
    }
    public var hasEmploymentDetail: Bool?
    public var hasBankAccountDetail: Bool?
    public var kycStatus: KycStatus?

    public init(hasEmploymentDetail: Bool?, hasBankAccountDetail: Bool?, kycStatus: KycStatus?) {
        self.hasEmploymentDetail = hasEmploymentDetail
        self.hasBankAccountDetail = hasBankAccountDetail
        self.kycStatus = kycStatus
    }


}

