//
// FinancialAccountSlim.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FinancialAccountSlim: Codable {

    public var financialInstitutionName: String?
    public var name: String?
    public var number: String?
    public var isSalaryAccount: Bool?

    public init(financialInstitutionName: String?, name: String?, number: String?, isSalaryAccount: Bool?) {
        self.financialInstitutionName = financialInstitutionName
        self.name = name
        self.number = number
        self.isSalaryAccount = isSalaryAccount
    }


}

