//
// FinancialAccountSlim.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FinancialAccountSlim: Codable {

    public enum AccountType: String, Codable { 
        case unknown = "UNKNOWN"
        case bank = "BANK"
        case creditCard = "CREDIT_CARD"
        case loan = "LOAN"
        case investment = "INVESTMENT"
        case mortgage = "MORTGAGE"
        case asset = "ASSET"
        case liability = "LIABILITY"
        case bills = "BILLS"
        case insurance = "INSURANCE"
        case loyalty = "LOYALTY"
    }
    public enum AssetType: String, Codable { 
        case unknown = "UNKNOWN"
        case asset = "ASSET"
        case liability = "LIABILITY"
    }
    public var financialAccountId: Int?
    public var name: String?
    public var nickname: String?
    public var number: String?
    public var accountType: AccountType?
    public var assetType: AssetType?

    public init(financialAccountId: Int?, name: String?, nickname: String?, number: String?, accountType: AccountType?, assetType: AssetType?) {
        self.financialAccountId = financialAccountId
        self.name = name
        self.nickname = nickname
        self.number = number
        self.accountType = accountType
        self.assetType = assetType
    }


}

