//
// GetAddressResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetAddressResponse: Codable {

    public enum State: String, Codable { 
        case nsw = "NSW"
        case qld = "QLD"
        case sa = "SA"
        case tas = "TAS"
        case vic = "VIC"
        case wa = "WA"
        case act = "ACT"
        case nt = "NT"
    }
    public var address: String?
    public var latitude: Double?
    public var longitude: Double?
    public var postCode: String?
    public var state: State?
    public var country: String?

    public init(address: String?, latitude: Double?, longitude: Double?, postCode: String?, state: State?, country: String?) {
        self.address = address
        self.latitude = latitude
        self.longitude = longitude
        self.postCode = postCode
        self.state = state
        self.country = country
    }


}

