//
// GetAddressResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetAddressResponse: Codable {

    public var address: String?
    public var suburb: String?

    public var postCode: String?
    public var state: String?
    public var country: String?

    public init(address: String?, suburb: String?, postCode: String?, state: String?, country: String?) {
        self.address = address
        self.suburb = suburb
        self.postCode = postCode
        self.state = state
        self.country = country
    }


}

