//
// GetAppTokenResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetAppTokenResponse: Codable {

    public var accessToken: String?
    public var expiresInSeconds: Int?
    public var apiConnectionUrl: String?
    public var apiContentType: String?

    public init(accessToken: String?, expiresInSeconds: Int?, apiConnectionUrl: String?, apiContentType: String?) {
        self.accessToken = accessToken
        self.expiresInSeconds = expiresInSeconds
        self.apiConnectionUrl = apiConnectionUrl
        self.apiContentType = apiContentType
    }


}

