//
// GetBudgetSpendingsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetBudgetSpendingsResponse: Codable {

    public var spendings: [SlimTransactionResponse]?

    public init(spendings: [SlimTransactionResponse]?) {
        self.spendings = spendings
    }


}

