//
// GetConnectionUpdateResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetConnectionUpdateResponse: Codable {

    public var institutionId: String?
    public var shortName: String?
    public var passwordCaption: String?
    public var securityCodeCaption: String?
    public var secondaryLoginIdCaption: String?
    public var accessToken: String?
    public var expiresInSeconds: Int?
    public var apiConnectionUrl: String?
    public var apiContentType: String?

    public init(institutionId: String?, shortName: String?, passwordCaption: String?, securityCodeCaption: String?, secondaryLoginIdCaption: String?, accessToken: String?, expiresInSeconds: Int?, apiConnectionUrl: String?, apiContentType: String?) {
        self.institutionId = institutionId
        self.shortName = shortName
        self.passwordCaption = passwordCaption
        self.securityCodeCaption = securityCodeCaption
        self.secondaryLoginIdCaption = secondaryLoginIdCaption
        self.accessToken = accessToken
        self.expiresInSeconds = expiresInSeconds
        self.apiConnectionUrl = apiConnectionUrl
        self.apiContentType = apiContentType
    }


}

