//
// GetFinancialInstitutionResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetFinancialInstitutionResponse: Codable {

    public var institutions: [GetFinancialInstitution]?
    public var warningMessage: String?
    public var disableMessage: String?

    public init(institutions: [GetFinancialInstitution]?, warningMessage: String?, disableMessage: String?) {
        self.institutions = institutions
        self.warningMessage = warningMessage
        self.disableMessage = disableMessage
    }


}

