//
// GetFinancialInstitution.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetFinancialInstitution: Codable {

    public var _id: String?
    public var shortName: String?
    public var loginIdCaption: String?
    public var passwordCaption: String?
    public var authorization: String?
    public var securityCodeCaption: String?
    public var secondaryLoginIdCaption: String?
    public var squareLogoUrl: String?
    public var fullLogoUrl: String?
    public var disabled: Bool?
    public var isWarning: Bool?
    public var displayOrder: Int?

    public init(_id: String?, shortName: String?, loginIdCaption: String?, passwordCaption: String?, authorization: String?, securityCodeCaption: String?, secondaryLoginIdCaption: String?, squareLogoUrl: String?, fullLogoUrl: String?, disabled: Bool?, isWarning: Bool?, displayOrder: Int?) {
        self._id = _id
        self.shortName = shortName
        self.loginIdCaption = loginIdCaption
        self.passwordCaption = passwordCaption
        self.authorization = authorization
        self.securityCodeCaption = securityCodeCaption
        self.secondaryLoginIdCaption = secondaryLoginIdCaption
        self.squareLogoUrl = squareLogoUrl
        self.fullLogoUrl = fullLogoUrl
        self.disabled = disabled
        self.isWarning = isWarning
        self.displayOrder = displayOrder
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case shortName
        case loginIdCaption
        case passwordCaption
        case authorization
        case securityCodeCaption
        case secondaryLoginIdCaption
        case squareLogoUrl
        case fullLogoUrl
        case disabled
        case isWarning
        case displayOrder
    }


}

