//
// GetLendingOverviewResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetLendingOverviewResponse: Codable {

    public var withdrawableAmount: Double?
    public var eligibility: Eligibility?
    public var loanTranscations: [LoanTransaction]?

    public init(withdrawableAmount: Double?, eligibility: Eligibility?, loanTranscations: [LoanTransaction]?) {
        self.withdrawableAmount = withdrawableAmount
        self.eligibility = eligibility
        self.loanTranscations = loanTranscations
    }


}

