//
// GetRecurringBillResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetRecurringBillResponse: Codable {

    public enum RecurringFrequency: String, Codable { 
        case weekly = "Weekly"
        case fortnightly = "Fortnightly"
        case monthly = "Monthly"
        case bimonthly = "Bimonthly"
        case quarterly = "Quarterly"
        case halfYearly = "HalfYearly"
        case yearly = "Yearly"
    }
    public var _id: Int?
    public var _description: String?
    public var merchant: String?
    public var merchantLogoUrl: String?
    public var amount: Double?
    public var startDate: String?
    public var endDate: String?
    public var recurringFrequency: RecurringFrequency?
    public var isAddedByUser: Bool?

    public init(_id: Int?, _description: String?, merchant: String?, merchantLogoUrl: String?, amount: Double?, startDate: String?, endDate: String?, recurringFrequency: RecurringFrequency?, isAddedByUser: Bool?) {
        self._id = _id
        self._description = _description
        self.merchant = merchant
        self.merchantLogoUrl = merchantLogoUrl
        self.amount = amount
        self.startDate = startDate
        self.endDate = endDate
        self.recurringFrequency = recurringFrequency
        self.isAddedByUser = isAddedByUser
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case _description = "description"
        case merchant
        case merchantLogoUrl
        case amount
        case startDate
        case endDate
        case recurringFrequency
        case isAddedByUser
    }


}

