//
// GetRepaymentOptionsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetRepaymentOptionsResponse: Codable {

    public var oneTimeRepayment: InstallmentDetail?
    public var multiRepaymentOptions: [MultipleRepayment]?
    public var multiRepaymentAttention: String?

    public init(oneTimeRepayment: InstallmentDetail?, multiRepaymentOptions: [MultipleRepayment]?, multiRepaymentAttention: String?) {
        self.oneTimeRepayment = oneTimeRepayment
        self.multiRepaymentOptions = multiRepaymentOptions
        self.multiRepaymentAttention = multiRepaymentAttention
    }


}

