//
// GetRefreshConnectionResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetRefreshConnectionResponse: Codable {

    public var jobId: String?

    public init(jobId: String?) {
        self.jobId = jobId
    }


}

