//
// GetSpendingOverviewResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetSpendingOverviewResponse: Codable {

    public var lastSuccessfulUpdatedAtUtc: String?
    public var overviewCard: SpendingOverviewCard?
    public var upcomingBills: [GetUpcomingBillResponse]?
    public var topCategoriesAmount: [CategoryAmountStatResponse]?
    public var recentTransactions: [SlimTransactionResponse]?

    public init(lastSuccessfulUpdatedAtUtc: String?, overviewCard: SpendingOverviewCard?, upcomingBills: [GetUpcomingBillResponse]?, topCategoriesAmount: [CategoryAmountStatResponse]?, recentTransactions: [SlimTransactionResponse]?) {
        self.lastSuccessfulUpdatedAtUtc = lastSuccessfulUpdatedAtUtc
        self.overviewCard = overviewCard
        self.upcomingBills = upcomingBills
        self.topCategoriesAmount = topCategoriesAmount
        self.recentTransactions = recentTransactions
    }


}

