//
// GetSpendingOverviewResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetSpendingOverviewResponse: Codable {

    public var upcomingBills: [GetUpcomingBillResponse]?
    public var topCategoriesAmount: [CategoryAmountStatResponse]?
    public var recentTransactions: [SlimTransactionResponse]?

    public init(upcomingBills: [GetUpcomingBillResponse]?, topCategoriesAmount: [CategoryAmountStatResponse]?, recentTransactions: [SlimTransactionResponse]?) {
        self.upcomingBills = upcomingBills
        self.topCategoriesAmount = topCategoriesAmount
        self.recentTransactions = recentTransactions
    }


}

