//
// GetSpendingCategoryResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetSpendingCategoryResponse: Codable {

    public var monthAmountStats: [MonthAmountStatResponse]?
    public var categoryAmountStats: [CategoryAmountStatResponse]?

    public init(monthAmountStats: [MonthAmountStatResponse]?, categoryAmountStats: [CategoryAmountStatResponse]?) {
        self.monthAmountStats = monthAmountStats
        self.categoryAmountStats = categoryAmountStats
    }
}

