//
// GetSpendingStatusResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetSpendingStatusResponse: Codable {

    public enum TransactionStatus: String, Codable { 
        case received = "Received"
        case categorising = "Categorising"
        case ready = "Ready"
        case noData = "NoData"
    }
    public var transactionStatus: TransactionStatus?

    public init(transactionStatus: TransactionStatus?) {
        self.transactionStatus = transactionStatus
    }


}

