//
// GetUserMoneySoftResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetUserMoneySoftResponse: Codable {

    public var msUsername: String?
    public var msPassword: String?

    public init(msUsername: String?, msPassword: String?) {
        self.msUsername = msUsername
        self.msPassword = msPassword
    }


}

