//
// GetUserKycResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetUserKycResponse: Codable {

    public var applicantId: String?
    public var kycStatus: String?
    public var sdkToken: String?

    public init(applicantId: String?, kycStatus: String?, sdkToken: String?) {
        self.applicantId = applicantId
        self.kycStatus = kycStatus
        self.sdkToken = sdkToken
    }


}

