//
// GetUserDetailResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetUserDetailResponse: Codable {

    public var firstName: String?
    public var lastName: String?
    public var mobile: String?
    public var dateOfBirth: Date?
    public var residentialAddress: String?
    public var maritalStatus: String?
    public var numberOfDependents: String?
    public var hasVerifiedKyc: Bool?
    public var state: String?

    public init(firstName: String?, lastName: String?, mobile: String?, dateOfBirth: Date?, residentialAddress: String?, maritalStatus: String?, numberOfDependents: String?, hasVerifiedKyc: Bool?, state: String?) {
        self.firstName = firstName
        self.lastName = lastName
        self.mobile = mobile
        self.dateOfBirth = dateOfBirth
        self.residentialAddress = residentialAddress
        self.maritalStatus = maritalStatus
        self.numberOfDependents = numberOfDependents
        self.hasVerifiedKyc = hasVerifiedKyc
        self.state = state
    }


}

