//
// LoanTransaction.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct LoanTransaction: Codable {

    public var amount: Double?
    public var fee: Double?
    public var date: Date?
    public var loanAgreementUrl: String?
    public var directDebitAgreementUrl: String?

    public init(amount: Double?, fee: Double?, date: Date?, loanAgreementUrl: String?, directDebitAgreementUrl: String?) {
        self.amount = amount
        self.fee = fee
        self.date = date
        self.loanAgreementUrl = loanAgreementUrl
        self.directDebitAgreementUrl = directDebitAgreementUrl
    }


}

