//
// LoanTransaction.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct LoanTransaction: Codable {

    public var amount: Double?
    public var fee: Double?
    public var date: String?
    public var loanType: String?
    public var loanAgreement: String?
    public var directDebitAgreement: String?

    public init(amount: Double?, fee: Double?, date: String?, loanType: String?, loanAgreement: String?, directDebitAgreement: String?) {
        self.amount = amount
        self.fee = fee
        self.date = date
        self.loanType = loanType
        self.loanAgreement = loanAgreement
        self.directDebitAgreement = directDebitAgreement
    }


}

