//
// LoanActivity.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct LoanActivity: Codable {

    public enum ModelType: String, Codable { 
        case cashout = "Cashout"
        case repayment = "Repayment"
    }
    public var amount: Double?
    public var date: String?
    public var type: ModelType?

    public init(amount: Double?, date: String?, type: ModelType?) {
        self.amount = amount
        self.date = date
        self.type = type
    }


}

