//
// MonthAmountStatResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MonthAmountStatResponse: Codable {

    public var amount: Double?
    public var month: String?

    public init(amount: Double?, month: String?) {
        self.amount = amount
        self.month = month
    }


}

