//
// MultipleRepayment.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MultipleRepayment: Codable {

    public var installments: [InstallmentDetail]?

    public init(installments: [InstallmentDetail]?) {
        self.installments = installments
    }


}

