//
// PostWorksheetRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PostWorksheetRequest: Codable {

    public var email: String
    public var worksheets: [Worksheet]?

    public init(email: String, worksheets: [Worksheet]?) {
        self.email = email
        self.worksheets = worksheets
    }


}

