//
// PostLogRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PostLogRequest: Codable {

    public enum ModelType: String, Codable { 
        case debug = "Debug"
        case error = "Error"
        case info = "Info"
    }
    
    public var deviceId: String?
    public var type: ModelType?
    public var message: String?
    public var event: String
    public var bankName: String?

    public init(deviceId: String?, type: ModelType?, message: String?, event: String, bankName: String?) {
        self.deviceId = deviceId
        self.type = type
        self.message = message
        self.event = event
        self.bankName = bankName
    }
    
}

