//
// PostLoanRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PostLoanRequest: Codable {

    public var amount: Int?
    public var fee: Int?
    public var agreeLoanAgreement: Bool?
    public var installments: [Repayment]?

    public init(amount: Int?, fee: Int?, agreeLoanAgreement: Bool?, installments: [Repayment]?) {
        self.amount = amount
        self.fee = fee
        self.agreeLoanAgreement = agreeLoanAgreement
        self.installments = installments
    }


}

