//
// PostPushNotificationRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PostPushNotificationRequest: Codable {

    public enum DeviceType: String, Codable { 
        case ios = "iOS"
        case android = "Android"
        case unknown = "Unknown"
    }
    public var deviceId: String?
    public var firebasePushNotificationToken: String?
    public var applePushNotificationToken: String?
    public var deviceType: DeviceType?

    public init(deviceId: String?, firebasePushNotificationToken: String?, applePushNotificationToken: String?, deviceType: DeviceType?) {
        self.deviceId = deviceId
        self.firebasePushNotificationToken = firebasePushNotificationToken
        self.applePushNotificationToken = applePushNotificationToken
        self.deviceType = deviceType
    }


}

