//
// PostSalaryTransactionsRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PostSalaryTransactionsRequest: Codable {

    public enum PayFrequency: String, Codable { 
        case weekly = "Weekly"
        case fortnightly = "Fortnightly"
        case monthly = "Monthly"
    }
    public var salaryTransactionIDs: [Int]?
    public var payFrequency: PayFrequency?
    public var noSalary: Bool?
    public var isInAnotherBank: Bool?

    public init(salaryTransactionIDs: [Int]?, payFrequency: PayFrequency?, noSalary: Bool?, isInAnotherBank: Bool?) {
        self.salaryTransactionIDs = salaryTransactionIDs
        self.payFrequency = payFrequency
        self.noSalary = noSalary
        self.isInAnotherBank = isInAnotherBank
    }


}

