//
// PostConnectionJobRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PostConnectionJobRequest: Codable {

    public var jobId: String
    public var institutionId: String

    public init(jobId: String, institutionId: String) {
        self.jobId = jobId
        self.institutionId = institutionId
    }


}

