//
// PutResetPasswordRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PutResetPasswordRequest: Codable {

    public var email: String
    public var verificationCode: String
    public var newPassword: String

    public init(email: String, verificationCode: String, newPassword: String) {
        self.email = email
        self.verificationCode = verificationCode
        self.newPassword = newPassword
    }


}

