//
// PutUserOnfidoKycRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PutUserOnfidoKycRequest: Codable {

    public var firstName: String
    public var lastName: String
    public var dateOfBirth: Date?
    public var residentialAddress: String

    public init(firstName: String, lastName: String, dateOfBirth: Date?, residentialAddress: String) {
        self.firstName = firstName
        self.lastName = lastName
        self.dateOfBirth = dateOfBirth
        self.residentialAddress = residentialAddress
    }


}

