//
// PutUserSingupVerificationCodeRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PutUserSingupVerificationCodeRequest: Codable {

    public var code: String

    public init(code: String) {
        self.code = code
    }


}

