//
// PutUserEmployerRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PutUserEmployerRequest: Codable {

    public enum EmploymentType: String, Codable { 
        case fulltime = "Fulltime"
        case parttime = "Parttime"
        case casual = "Casual"
        case selfEmployed = "SelfEmployed"
        case contractor = "Contractor"
        case onDemand = "OnDemand"
        case centrelink = "Centrelink"
    }
    public enum WorkingLocation: String, Codable { 
        case fromFixedLocation = "FromFixedLocation"
        case fromMultipleLocations = "FromMultipleLocations"
        case fromHomeOrRemote = "FromHomeOrRemote"
    }
    public var employerName: String?
    public var employmentType: EmploymentType?
    public var workingLocation: WorkingLocation?
    public var latitude: Double?
    public var longitude: Double?
    public var address: String?
    public var state: String?
    public var country: String?
    public var postCode: String?
/*
    public init(employerName: String?, employmentType: EmploymentType?, workingLocation: WorkingLocation?, latitude: Double?, longitude: Double?, address: String?, state: String?, country: String?, postCode: String?) {
        self.employerName = employerName
        self.employmentType = employmentType
        self.workingLocation = workingLocation
        self.latitude = latitude
        self.longitude = longitude
        self.address = address
        self.state = state
        self.country = country
        self.postCode = postCode
    }
*/
  
    public init(employerName: String?, employmentType: EmploymentType?, address: String?) {
           self.employerName = employerName
           self.employmentType = employmentType
           self.address = address
        
       }
    
}

