//
// PutUserEmployerRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PutUserEmployerRequest: Codable {

    public enum EmploymentType: String, Codable { 
        case fulltime = "Fulltime"
        case parttime = "Parttime"
        case casual = "Casual"
        case selfEmployed = "SelfEmployed"
        case contractor = "Contractor"
        case onDemand = "OnDemand"
        case centrelink = "Centrelink"
    }

    public var employerName: String?
    public var employmentType: EmploymentType?
    public var address: String?
    public var state: String?
    public var country: String?
    public var postCode: String?
  
    public init(employerName: String?, employmentType: EmploymentType?, address: String?) {
           self.employerName = employerName
           self.employmentType = employmentType
           self.address = address
        
       }
    
}

