//
// Repayment.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Repayment: Codable {

    public var amount: Double?
    public var fee: Double?
    public var date: Date?

    public init(amount: Double?, fee: Double?, date: Date?) {
        self.amount = amount
        self.fee = fee
        self.date = date
    }


}

