//
// SlimTransactionResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SlimTransactionResponse: Codable {

    public enum CategoryCode: String, Codable { 
        case benefits = "Benefits"
        case bills = "Bills"
        case employmentIncome = "EmploymentIncome"
        case entertainment = "Entertainment"
        case financialServices = "FinancialServices"
        case fitness = "Fitness"
        case groceries = "Groceries"
        case health = "Health"
        case household = "Household"
        case ondemandIncome = "OndemandIncome"
        case others = "Others"
        case otherDeposit = "OtherDeposit"
        case restaurantsAndCafes = "RestaurantsAndCafes"
        case shopping = "Shopping"
        case secondaryIncome = "SecondaryIncome"
        case tobaccoAndAlcohol = "TobaccoAndAlcohol"
        case transport = "Transport"
        case travel = "Travel"
        case workAndEducation = "WorkAndEducation"
    }
    public var _description: String?
    public var amount: Double?
    public var date: String?
    public var categoryTitle: String?
    public var categoryCode: CategoryCode?
    public var merchant: String?
    public var merchantLogoUrl: String?
    public var financialAccountName: String?
    public var financialInstitutionLogoUrl: String?

    public init(_description: String?, amount: Double?, date: String?, categoryTitle: String?, categoryCode: CategoryCode?, merchant: String?, merchantLogoUrl: String?, financialAccountName: String?, financialInstitutionLogoUrl: String?) {
        self._description = _description
        self.amount = amount
        self.date = date
        self.categoryTitle = categoryTitle
        self.categoryCode = categoryCode
        self.merchant = merchant
        self.merchantLogoUrl = merchantLogoUrl
        self.financialAccountName = financialAccountName
        self.financialInstitutionLogoUrl = financialInstitutionLogoUrl
    }

    public enum CodingKeys: String, CodingKey { 
        case _description = "description"
        case amount
        case date
        case categoryTitle
        case categoryCode
        case merchant
        case merchantLogoUrl
        case financialAccountName
        case financialInstitutionLogoUrl
    }


}

