//
// UserBudget.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UserBudget: Codable {

    public var _id: Int?
    public var categoryTitle: String?
    public var categoryCode: String?
    public var estimatedBudget: Int?
    public var actualSpending: Int?
    public var hide: Bool?

    public init(_id: Int?, categoryTitle: String?, categoryCode: String?, estimatedBudget: Int?, actualSpending: Int?, hide: Bool?) {
        self._id = _id
        self.categoryTitle = categoryTitle
        self.categoryCode = categoryCode
        self.estimatedBudget = estimatedBudget
        self.actualSpending = actualSpending
        self.hide = hide
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case categoryTitle
        case categoryCode
        case estimatedBudget
        case actualSpending
        case hide
    }


}

