//
// UserFinancialAccountsLinkingResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UserFinancialAccountsLinkingResponse: Codable {

    public var hasLinkedAnyFinancialAccounts: Bool?

    public init(hasLinkedAnyFinancialAccounts: Bool?) {
        self.hasLinkedAnyFinancialAccounts = hasLinkedAnyFinancialAccounts
    }


}

