//
// UserAction.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UserAction: Codable {

    public enum Action: String, Codable { 
        case resolveNameConflict = "ResolveNameConflict"
        case turnupToWork = "TurnupToWork"
        case turnOnLocation = "TurnOnLocation"
        case uploadRecentTimesheet = "UploadRecentTimesheet"
    }
    public var action: Action?
    public var title: String?
    public var _description: String?
    public var link: String?

    public init(action: Action?, title: String?, _description: String?, link: String?) {
        self.action = action
        self.title = title
        self._description = _description
        self.link = link
    }

    public enum CodingKeys: String, CodingKey { 
        case action
        case title
        case _description = "description"
        case link
    }


}

