# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
workspace 'Cheq'

def swift4_pods
  pre_install do |installer|
    installer.analysis_result.specifications.each do |s|
      if s.name == 'Alamofire' || s.name == 'CocoaLumberjack' || s.name == 'SwiftEntryKit'
        s.swift_version = '4.0'
      end
    end
  end
end

def shared_pods
  # Pods for Cheq
  pod 'SwiftKeychainWrapper'
  pod 'Charts', '~> 3.3'
  pod 'NavigationDropdownMenu'
  pod 'Hex'
  pod 'SwiftSpinner'
  pod 'PopOverMenu'
  pod 'Alamofire'
  pod 'PromiseKit'
  pod 'Validator', '~> 3.2'
  pod 'PopupDialog', '~> 1.0.0'
  pod 'DateToolsSwift'
  pod 'UDatePicker', '~> 1.1.1'
  pod 'SearchTextField', '~> 1.2.0'
  pod 'PullToRefreshKit'
  pod 'SDWebImage', '~> 5.0'
  pod 'SwiftEntryKit', '1.1.0'
  
  # intercom
  pod 'Intercom', '~> 5.4.1'
  
  # Pod for BlueDot SDK
  pod 'BluedotPointSDK', '15.0.0'
  
  # Pod dependency from MoneySoft
  pod 'Mantle'
  pod 'PromisesObjC'
  pod 'FMDB'
  pod 'CocoaLumberjack/Swift','<=3.4.2'
  pod 'REValidation'
  pod 'Obfuscator'
  pod 'SQLCipher'
  pod 'sqlite3', '<= 3.27.2'
  pod 'OpenSSL-Universal'
  
  #Fabrics + Crashlytics
  pod 'Fabric', '~> 1.10.2'
  pod 'Crashlytics', '~> 3.14.0'
  
  # Firebase pods
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/InAppMessagingDisplay'
  pod 'Firebase/Analytics'
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Facebook'
  pod 'Firebase/RemoteConfig'
  
  # Onfido pod
  pod 'Onfido'
end

target 'Cheq' do
  project 'Cheq.xcodeproj'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  swift4_pods
  shared_pods

  target 'CheqTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'SnapshotTest'
  end
end

target 'CheqProd' do
  project 'Cheq.xcodeproj'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  swift4_pods
  shared_pods
end

target 'CheqDemo' do
  project 'Cheq.xcodeproj'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  swift4_pods
  shared_pods
end
