# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
workspace 'Cheq'



def swift4_pods
  pre_install do |installer|
    installer.analysis_result.specifications.each do |s|
      if s.name == 'Alamofire' || s.name == 'CocoaLumberjack' || s.name == 'SwiftEntryKit'
        s.swift_version = '4.2'
      end
    end
  end
end

def shared_pods
  # Pods for Cheq
  pod 'SwiftKeychainWrapper'
  pod 'Charts', '~> 3.3'
  pod 'NavigationDropdownMenu'
  pod 'Hex'
  pod 'SVProgressHUD'
  pod 'PopOverMenu'
  pod 'Alamofire', '~> 4.9.0'
  pod 'PromiseKit'
  pod 'Validator', '~> 3.2'
  pod 'PopupDialog', '~> 1.0.0'
  pod 'DateToolsSwift'
  pod 'UDatePicker', '~> 1.1.1'
  pod 'SearchTextField', '~> 1.2.0'
  pod 'PullToRefreshKit'
  pod 'SDWebImage', '~> 5.0'
  pod 'SwiftEntryKit', '1.1.0'
  
  # intercom
  pod 'Intercom', '~> 5.4.1'
  
  # Pods for MobileSDKDemo
	pod 'Mantle'
	pod 'PromisesObjC'
	pod 'FMDB'
	pod 'REValidation'
	# pod 'MIHCrypto'
	pod 'Obfuscator'
	pod 'SQLCipher'
	pod 'sqlite3','~> 3.27.2'
	pod 'CocoaLumberjack', '<= 3.4.2'
	pod 'OpenSSL-Universal'
  
  #Fabrics + Crashlytics
  pod 'Fabric', '~> 1.10.2'
  pod 'Crashlytics', '~> 3.14.0'
  
  # Firebase pods
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/InAppMessagingDisplay'
  pod 'Firebase/Analytics'
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Facebook'
  pod 'Firebase/RemoteConfig'
  
    # Onfido pod
  pod 'Onfido'
  
  # Mixpanel pod
  pod 'Mixpanel-swift'
  
  #A subclass of UILabel to allow you adding one or more hyperlinks to the texts
  pod 'FRHyperLabel'
  
  #Codeless drop-in universal library allows to prevent issues of keyboard sliding up and cover UITextField/UITextView. Neither need to write any code nor any setup required and much more.
  pod 'IQKeyboardManagerSwift'
  
end

target 'Cheq' do
  #project 'Cheq.xcodeproj'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  swift4_pods
  shared_pods

  target 'CheqTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'SnapshotTest'
  end
end

target 'CheqProd' do
  #project 'Cheq.xcodeproj'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  swift4_pods
  shared_pods
end

target 'CheqDemo' do
  #project 'Cheq.xcodeproj'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  swift4_pods
  shared_pods
end

