//
// CategoryAmountStatResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CategoryAmountStatResponse: Codable {

    public var categoryId: Int?
    public var title: String?
    public var categoryCode: String?
    public var categoryAmount: Double?
    public var totalAmount: Double?

    public init(categoryId: Int?, title: String?, categoryCode: String?, categoryAmount: Double?, totalAmount: Double?) {
        self.categoryId = categoryId
        self.title = title
        self.categoryCode = categoryCode
        self.categoryAmount = categoryAmount
        self.totalAmount = totalAmount
    }


}

