//
// CategoryStat.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CategoryStat: Codable {

    public var category: String?
    public var numberOfTransactions: Int?
    public var sum: Double?

    public init(category: String?, numberOfTransactions: Int?, sum: Double?) {
        self.category = category
        self.numberOfTransactions = numberOfTransactions
        self.sum = sum
    }


}

