//
// DailyTransactionsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DailyTransactionsResponse: Codable {

    public var date: Date?
    public var transactions: [SlimTransactionResponse]?

    public init(date: Date?, transactions: [SlimTransactionResponse]?) {
        self.date = date
        self.transactions = transactions
    }


}

