//
// GetAddressResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetAddressResponse: Codable {

    public var address: String?
    public var latitude: Double?
    public var longitude: Double?

    public init(address: String?, latitude: Double?, longitude: Double?) {
        self.address = address
        self.latitude = latitude
        self.longitude = longitude
    }


}

