//
// GetEmployerPlaceResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetEmployerPlaceResponse: Codable {

    public var name: String?
    public var address: String?
    public var latitude: Double?
    public var longitude: Double?

    public init(name: String?, address: String?, latitude: Double?, longitude: Double?) {
        self.name = name
        self.address = address
        self.latitude = latitude
        self.longitude = longitude
    }


}

