//
// GetRecurringBillResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetRecurringBillResponse: Codable {

    public var _id: Int?
    public var _description: String?
    public var merchant: String?
    public var amount: Double?
    public var startDate: String?
    public var endDate: String?
    public var recurringFrequency: String?

    public init(_id: Int?, _description: String?, merchant: String?, amount: Double?, startDate: String?, endDate: String?, recurringFrequency: String?) {
        self._id = _id
        self._description = _description
        self.merchant = merchant
        self.amount = amount
        self.startDate = startDate
        self.endDate = endDate
        self.recurringFrequency = recurringFrequency
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case _description = "description"
        case merchant
        case amount
        case startDate
        case endDate
        case recurringFrequency
    }


}

