//
// GetUpcomingBillResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetUpcomingBillResponse: Codable {

    public var _description: String?
    public var merchant: String?
    public var amount: Double?
    public var dueDate: String?

    public init(_description: String?, merchant: String?, amount: Double?, dueDate: String?) {
        self._description = _description
        self.merchant = merchant
        self.amount = amount
        self.dueDate = dueDate
    }

    public enum CodingKeys: String, CodingKey { 
        case _description = "description"
        case merchant
        case amount
        case dueDate
    }


}

