//
// GetUserBudgetResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetUserBudgetResponse: Codable {

    public var overallSpendingBudget: Double?
    public var overallActualSpending: Double?
    public var userBudgets: [UserBudget]?

    public init(overallSpendingBudget: Double?, overallActualSpending: Double?, userBudgets: [UserBudget]?) {
        self.overallSpendingBudget = overallSpendingBudget
        self.overallActualSpending = overallActualSpending
        self.userBudgets = userBudgets
    }


}

