//
// GetUserBudgetResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetUserBudgetResponse: Codable {

    public enum RecurringFrequency: String, Codable { 
        case weekly = "Weekly"
        case fortnightly = "Fortnightly"
        case monthly = "Monthly"
        case bimonthly = "Bimonthly"
        case quarterly = "Quarterly"
        case halfYearly = "HalfYearly"
        case yearly = "Yearly"
    }
    public var startDate: String?
    public var recurringFrequency: RecurringFrequency?
    public var userBudgets: [UserBudget]?

    public init(startDate: String?, recurringFrequency: RecurringFrequency?, userBudgets: [UserBudget]?) {
        self.startDate = startDate
        self.recurringFrequency = recurringFrequency
        self.userBudgets = userBudgets
    }


}

