//
// GetUserBluedotResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetUserBluedotResponse: Codable {

    public var bluedotProjectApiKey: String?

    public init(bluedotProjectApiKey: String?) {
        self.bluedotProjectApiKey = bluedotProjectApiKey
    }


}

