//
// GetUserBudgetResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetUserBudgetResponse: Codable {

    public var startDate: String?
    public var recurringFrequency: String?
    public var requireSetupProcess: Bool?
    public var totalBudget: Double?
    public var totalSpending: Double?
    public var userBudgets: [UserBudget]?

    public init(startDate: String?, recurringFrequency: String?, requireSetupProcess: Bool?, totalBudget: Double?, totalSpending: Double?, userBudgets: [UserBudget]?) {
        self.startDate = startDate
        self.recurringFrequency = recurringFrequency
        self.requireSetupProcess = requireSetupProcess
        self.totalBudget = totalBudget
        self.totalSpending = totalSpending
        self.userBudgets = userBudgets
    }


}

