//
// GetUserDetailResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetUserDetailResponse: Codable {

    public var firstName: String?
    public var lastName: String?
    public var mobile: String?
    public var residentialAddress: String?
    public var hasVerifiedKyc: Bool?

    public init(firstName: String?, lastName: String?, mobile: String?, residentialAddress: String?, hasVerifiedKyc: Bool?) {
        self.firstName = firstName
        self.lastName = lastName
        self.mobile = mobile
        self.residentialAddress = residentialAddress
        self.hasVerifiedKyc = hasVerifiedKyc
    }


}

