//
// MoneySoftVisibleMessageRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MoneySoftVisibleMessageRequest: Codable {

    public var title: String?
    public var message: String?

    public init(title: String?, message: String?) {
        self.title = title
        self.message = message
    }


}

