//
// PostFinancialInstitutionRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PostFinancialInstitutionRequest: Codable {

    public var financialInstitutionId: Int?
    public var providerInstitutionId: Int?
    public var name: String?
    public var alias: String?
    public var displayName: String?
    public var order: Int?
    public var isActive: Bool?
    public var financialServiceId: Int?
    public var isMFA: Bool?
    public var providerId: Int?

    public init(financialInstitutionId: Int?, providerInstitutionId: Int?, name: String?, alias: String?, displayName: String?, order: Int?, isActive: Bool?, financialServiceId: Int?, isMFA: Bool?, providerId: Int?) {
        self.financialInstitutionId = financialInstitutionId
        self.providerInstitutionId = providerInstitutionId
        self.name = name
        self.alias = alias
        self.displayName = displayName
        self.order = order
        self.isActive = isActive
        self.financialServiceId = financialServiceId
        self.isMFA = isMFA
        self.providerId = providerId
    }


}

