//
// PostFinancialAccountRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PostFinancialAccountRequest: Codable {

    public var financialAccountId: Int?
    public var providerAccountId: String?
    public var financialInstitutionId: Int?
    public var providerInstitutionId: Int?
    public var providerContainerId: String?
    public var name: String?
    public var nickname: String?
    public var number: String?
    public var balance: Double?
    public var disabled: Bool?
    public var type: String?
    public var assetType: String?
    public var source: String?

    public init(financialAccountId: Int?, providerAccountId: String?, financialInstitutionId: Int?, providerInstitutionId: Int?, providerContainerId: String?, name: String?, nickname: String?, number: String?, balance: Double?, disabled: Bool?, type: String?, assetType: String?, source: String?) {
        self.financialAccountId = financialAccountId
        self.providerAccountId = providerAccountId
        self.financialInstitutionId = financialInstitutionId
        self.providerInstitutionId = providerInstitutionId
        self.providerContainerId = providerContainerId
        self.name = name
        self.nickname = nickname
        self.number = number
        self.balance = balance
        self.disabled = disabled
        self.type = type
        self.assetType = assetType
        self.source = source
    }


}

