//
// PostGeoLocationRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PostGeoLocationRequest: Codable {

    public var token: String?
    public var latitude: Double?
    public var longitude: Double?

    public init(token: String?, latitude: Double?, longitude: Double?) {
        self.token = token
        self.latitude = latitude
        self.longitude = longitude
    }


}

