//
// PutFinancialAccountRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PutFinancialAccountRequest: Codable {

    public var financialAccountId: Int?
    public var name: String?
    public var nickname: String?
    public var balance: Double?
    public var disabled: Bool?
    public var source: String?
    public var transactions: [PostFinancialTransactionRequest]?

    public init(financialAccountId: Int?, name: String?, nickname: String?, balance: Double?, disabled: Bool?, source: String?, transactions: [PostFinancialTransactionRequest]?) {
        self.financialAccountId = financialAccountId
        self.name = name
        self.nickname = nickname
        self.balance = balance
        self.disabled = disabled
        self.source = source
        self.transactions = transactions
    }


}

