//
// PutSpendingBudgetRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PutSpendingBudgetRequest: Codable {

    public var newSpendingBudget: Double?

    public init(newSpendingBudget: Double?) {
        self.newSpendingBudget = newSpendingBudget
    }


}

