//
// PutUserKycResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PutUserKycResponse: Codable {

    public var applicantId: String?
    public var sdkToken: String?
    public var sentOnfidoKycExpressChecked: Bool?
    public var hasKycFailed: Bool?
    public var hasKycCompleted: Bool?

    public init(applicantId: String?, sdkToken: String?, sentOnfidoKycExpressChecked: Bool?, hasKycFailed: Bool?, hasKycCompleted: Bool?) {
        self.applicantId = applicantId
        self.sdkToken = sdkToken
        self.sentOnfidoKycExpressChecked = sentOnfidoKycExpressChecked
        self.hasKycFailed = hasKycFailed
        self.hasKycCompleted = hasKycCompleted
    }


}

