//
// PutUserDetailRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PutUserDetailRequest: Codable {

    public var firstName: String
    public var lastName: String
    public var mobile: String
    public var residentialAddress: String

    public init(firstName: String, lastName: String, mobile: String, residentialAddress: String) {
        self.firstName = firstName
        self.lastName = lastName
        self.mobile = mobile
        self.residentialAddress = residentialAddress
    }


}

