//
// PutUserBudgetsRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PutUserBudgetsRequest: Codable {

    public enum RecurringFrequency: String, Codable { 
        case weekly = "Weekly"
        case fortnightly = "Fortnightly"
        case monthly = "Monthly"
        case bimonthly = "Bimonthly"
        case quarterly = "Quarterly"
        case halfYearly = "HalfYearly"
        case yearly = "Yearly"
    }
    public var startDate: Date?
    public var recurringFrequency: RecurringFrequency?
    public var newBudgetUpdates: [UserBudgetUpdate]?

    public init(startDate: Date?, recurringFrequency: RecurringFrequency?, newBudgetUpdates: [UserBudgetUpdate]?) {
        self.startDate = startDate
        self.recurringFrequency = recurringFrequency
        self.newBudgetUpdates = newBudgetUpdates
    }


}

