//
// PutUserKycResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PutUserKycResponse: Codable {

    public var applicantId: String?
    public var sdkToken: String?
    public var sentOnfidoKycExpressChecked: Bool?

    public init(applicantId: String?, sdkToken: String?, sentOnfidoKycExpressChecked: Bool?) {
        self.applicantId = applicantId
        self.sdkToken = sdkToken
        self.sentOnfidoKycExpressChecked = sentOnfidoKycExpressChecked
    }


}

