//
// PutUserRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PutUserRequest: Codable {

    public var detail: PutUserDetailRequest?
    public var employer: PutUserEmployerRequest?
    public var pushNotification: PostPushNotificationRequest?
    public var kyc: PutUserKycRequest?

    public init(detail: PutUserDetailRequest?, employer: PutUserEmployerRequest?, pushNotification: PostPushNotificationRequest?, kyc: PutUserKycRequest?) {
        self.detail = detail
        self.employer = employer
        self.pushNotification = pushNotification
        self.kyc = kyc
    }


}

