//
// PutUserDetailRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PutUserDetailRequest: Codable {

    public enum AgeRange: String, Codable { 
        case from18To24 = "From18To24"
        case from25To34 = "From25To34"
        case from35To54 = "From35To54"
        case from55To64 = "From55To64"
        case over65 = "Over65"
    }
    public enum MaritalStatus: String, Codable { 
        case single = "Single"
        case couple = "Couple"
    }
    public enum State: String, Codable { 
        case nsw = "NSW"
        case qld = "QLD"
        case sa = "SA"
        case tas = "TAS"
        case vic = "VIC"
        case wa = "WA"
        case act = "ACT"
        case nt = "NT"
    }
    public var firstName: String
    public var lastName: String
    public var ageRange: AgeRange?
    public var mobile: String
    public var maritalStatus: MaritalStatus?
    public var numberOfDependents: String?
    public var state: State?

    public init(firstName: String, lastName: String, ageRange: AgeRange?, mobile: String, maritalStatus: MaritalStatus?, numberOfDependents: String?, state: State?) {
        self.firstName = firstName
        self.lastName = lastName
        self.ageRange = ageRange
        self.mobile = mobile
        self.maritalStatus = maritalStatus
        self.numberOfDependents = numberOfDependents
        self.state = state
    }


}

