//
// PutUserGeolocationInstallDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PutUserGeolocationInstallDetails: Codable {

    public var installReference: String

    public init(installReference: String) {
        self.installReference = installReference
    }


}

