//
// SlimTransactionResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SlimTransactionResponse: Codable {

    public var _description: String?
    public var amount: Double?
    public var date: String?
    public var category: String?
    public var merchant: String?
    public var merchantLogoUrl: String?
    public var financialAccountName: String?
    public var financialInstitutionLogoUrl: String?

    public init(_description: String?, amount: Double?, date: String?, category: String?, merchant: String?, merchantLogoUrl: String?, financialAccountName: String?, financialInstitutionLogoUrl: String?) {
        self._description = _description
        self.amount = amount
        self.date = date
        self.category = category
        self.merchant = merchant
        self.merchantLogoUrl = merchantLogoUrl
        self.financialAccountName = financialAccountName
        self.financialInstitutionLogoUrl = financialInstitutionLogoUrl
    }

    public enum CodingKeys: String, CodingKey { 
        case _description = "description"
        case amount
        case date
        case category
        case merchant
        case merchantLogoUrl
        case financialAccountName
        case financialInstitutionLogoUrl
    }


}

