//
// UploadTimesheetResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UploadTimesheetResponse: Codable {

    public var fileName: String?

    public init(fileName: String?) {
        self.fileName = fileName
    }


}

