//
// UserLendingRequirement.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UserLendingRequirement: Codable {

    public var hasVerifiedKyc: Bool?
    public var hasConfirmedEmail: Bool?
    public var loanAgreement: String?
    public var directDebitAgreement: String?
    public var bankAcccountBsb: String?
    public var bankAcccountNumber: String?

    public init(hasVerifiedKyc: Bool?, hasConfirmedEmail: Bool?, loanAgreement: String?, directDebitAgreement: String?, bankAcccountBsb: String?, bankAcccountNumber: String?) {
        self.hasVerifiedKyc = hasVerifiedKyc
        self.hasConfirmedEmail = hasConfirmedEmail
        self.loanAgreement = loanAgreement
        self.directDebitAgreement = directDebitAgreement
        self.bankAcccountBsb = bankAcccountBsb
        self.bankAcccountNumber = bankAcccountNumber
    }


}

