//
// GetUserResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetUserResponse: Codable {

    public var email: String?
    public var firstName: String?
    public var middleName: String?
    public var lastName: String?
    public var residentialAddress: String?
    public var hasBeenOnBoarded: Bool?
    public var msUsername: String?
    public var msPassword: String?

    public init(email: String?, firstName: String?, middleName: String?, lastName: String?, residentialAddress: String?, hasBeenOnBoarded: Bool?, msUsername: String?, msPassword: String?) {
        self.email = email
        self.firstName = firstName
        self.middleName = middleName
        self.lastName = lastName
        self.residentialAddress = residentialAddress
        self.hasBeenOnBoarded = hasBeenOnBoarded
        self.msUsername = msUsername
        self.msPassword = msPassword
    }


}

