//
// PostFinancialTransactionRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PostFinancialTransactionRequest: Codable {

    public var transactionId: Int?
    public var accountId: Int?
    public var categoryId: Int?
    public var amount: Double?
    public var date: Date?
    public var isDeleted: Bool?
    public var isVerified: Bool?
    public var merchant: String?
    public var name: String?
    public var notes: String?
    public var possibleTransfer: Bool?
    public var type: String?
    public var source: String?

    public init(transactionId: Int?, accountId: Int?, categoryId: Int?, amount: Double?, date: Date?, isDeleted: Bool?, isVerified: Bool?, merchant: String?, name: String?, notes: String?, possibleTransfer: Bool?, type: String?, source: String?) {
        self.transactionId = transactionId
        self.accountId = accountId
        self.categoryId = categoryId
        self.amount = amount
        self.date = date
        self.isDeleted = isDeleted
        self.isVerified = isVerified
        self.merchant = merchant
        self.name = name
        self.notes = notes
        self.possibleTransfer = possibleTransfer
        self.type = type
        self.source = source
    }


}

