//
// PostWithdrawRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PostWithdrawRequest: Codable {

    public var bsb: String?
    public var accountNumber: String?
    public var amount: Double?

    public init(bsb: String?, accountNumber: String?, amount: Double?) {
        self.bsb = bsb
        self.accountNumber = accountNumber
        self.amount = amount
    }


}

