//
// PostFinancialAccountRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PostFinancialAccountRequest: Codable {

    public var financialAccountId: Int?
    public var providerAccountId: String?
    public var financialInstitutionId: Int?
    public var providerInstitutionId: Int?
    public var providerContainerId: String?
    public var name: String?
    public var nickname: String?
    public var number: String?
    public var balance: Double?
    public var isBalanceOnly: Bool?
    public var created: Date?
    public var disabled: Bool?
    public var isInBudget: Bool?
    public var isManualAccount: Bool?
    public var nextRefreshUtc: Date?
    public var lastSuccessfulUpdateUtc: Date?
    public var lastUpdateAttemptUtc: Date?
    public var providerLastSuccessfulUpdate: Date?
    public var type: String?
    public var assetCategory: String?
    public var assetType: String?

    public init(financialAccountId: Int?, providerAccountId: String?, financialInstitutionId: Int?, providerInstitutionId: Int?, providerContainerId: String?, name: String?, nickname: String?, number: String?, balance: Double?, isBalanceOnly: Bool?, created: Date?, disabled: Bool?, isInBudget: Bool?, isManualAccount: Bool?, nextRefreshUtc: Date?, lastSuccessfulUpdateUtc: Date?, lastUpdateAttemptUtc: Date?, providerLastSuccessfulUpdate: Date?, type: String?, assetCategory: String?, assetType: String?) {
        self.financialAccountId = financialAccountId
        self.providerAccountId = providerAccountId
        self.financialInstitutionId = financialInstitutionId
        self.providerInstitutionId = providerInstitutionId
        self.providerContainerId = providerContainerId
        self.name = name
        self.nickname = nickname
        self.number = number
        self.balance = balance
        self.isBalanceOnly = isBalanceOnly
        self.created = created
        self.disabled = disabled
        self.isInBudget = isInBudget
        self.isManualAccount = isManualAccount
        self.nextRefreshUtc = nextRefreshUtc
        self.lastSuccessfulUpdateUtc = lastSuccessfulUpdateUtc
        self.lastUpdateAttemptUtc = lastUpdateAttemptUtc
        self.providerLastSuccessfulUpdate = providerLastSuccessfulUpdate
        self.type = type
        self.assetCategory = assetCategory
        self.assetType = assetType
    }


}

