//
// LogosAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class LogosAPI {
    /**

     - parameter _id: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getBankLogo(_id: Int, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        getBankLogoWithRequestBuilder(_id: _id).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - GET /v1/Logos/institutions/{id}
     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     
     - parameter _id: (path)  

     - returns: RequestBuilder<Void> 
     */
    open class func getBankLogoWithRequestBuilder(_id: Int) -> RequestBuilder<Void> {
        var path = "/v1/Logos/institutions/{id}"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**

     - parameter _id: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getTransactionMerchantLogo(_id: String, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        getTransactionMerchantLogoWithRequestBuilder(_id: _id).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - GET /v1/Logos/transactions/{id}
     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     
     - parameter _id: (path)  

     - returns: RequestBuilder<Void> 
     */
    open class func getTransactionMerchantLogoWithRequestBuilder(_id: String) -> RequestBuilder<Void> {
        var path = "/v1/Logos/transactions/{id}"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
