//
// SpendingAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class SpendingAPI {
    /**

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getCurrentMonthSpending(completion: @escaping ((_ data: [GetSpendingResponse]?,_ error: Error?) -> Void)) {
        getCurrentMonthSpendingWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /v1/Spending/month
     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     - examples: [{contentType=application/json, example=[ {
  "merchant" : "merchant",
  "sum" : 1.4658129805029452,
  "transactedAt" : "transactedAt",
  "merchantLogoUrl" : "merchantLogoUrl",
  "category" : "category",
  "info" : "info"
}, {
  "merchant" : "merchant",
  "sum" : 1.4658129805029452,
  "transactedAt" : "transactedAt",
  "merchantLogoUrl" : "merchantLogoUrl",
  "category" : "category",
  "info" : "info"
} ]}]

     - returns: RequestBuilder<[GetSpendingResponse]> 
     */
    open class func getCurrentMonthSpendingWithRequestBuilder() -> RequestBuilder<[GetSpendingResponse]> {
        let path = "/v1/Spending/month"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<[GetSpendingResponse]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getCurrentWeekSpending(completion: @escaping ((_ data: [GetSpendingResponse]?,_ error: Error?) -> Void)) {
        getCurrentWeekSpendingWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /v1/Spending/week
     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     - examples: [{contentType=application/json, example=[ {
  "merchant" : "merchant",
  "sum" : 1.4658129805029452,
  "transactedAt" : "transactedAt",
  "merchantLogoUrl" : "merchantLogoUrl",
  "category" : "category",
  "info" : "info"
}, {
  "merchant" : "merchant",
  "sum" : 1.4658129805029452,
  "transactedAt" : "transactedAt",
  "merchantLogoUrl" : "merchantLogoUrl",
  "category" : "category",
  "info" : "info"
} ]}]

     - returns: RequestBuilder<[GetSpendingResponse]> 
     */
    open class func getCurrentWeekSpendingWithRequestBuilder() -> RequestBuilder<[GetSpendingResponse]> {
        let path = "/v1/Spending/week"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<[GetSpendingResponse]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getTodaySpending(completion: @escaping ((_ data: GetTodaySpendingResponse?,_ error: Error?) -> Void)) {
        getTodaySpendingWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /v1/Spending/today
     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     - examples: [{contentType=application/json, example={
  "totalIncome" : 6.027456183070403,
  "totalSpend" : 0.8008281904610115,
  "spending" : [ {
    "merchant" : "merchant",
    "sum" : 1.4658129805029452,
    "transactedAt" : "transactedAt",
    "merchantLogoUrl" : "merchantLogoUrl",
    "category" : "category",
    "info" : "info"
  }, {
    "merchant" : "merchant",
    "sum" : 1.4658129805029452,
    "transactedAt" : "transactedAt",
    "merchantLogoUrl" : "merchantLogoUrl",
    "category" : "category",
    "info" : "info"
  } ],
  "categoryStats" : [ {
    "sum" : 5.637376656633329,
    "category" : "category",
    "numberOfTransactions" : 5
  }, {
    "sum" : 5.637376656633329,
    "category" : "category",
    "numberOfTransactions" : 5
  } ]
}}]

     - returns: RequestBuilder<GetTodaySpendingResponse> 
     */
    open class func getTodaySpendingWithRequestBuilder() -> RequestBuilder<GetTodaySpendingResponse> {
        let path = "/v1/Spending/today"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<GetTodaySpendingResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
