//
// FirebaseAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class FirebaseAPI {
    /**

     - parameter email: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getToken(email: String, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        getTokenWithRequestBuilder(email: email).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - GET /v1/Firebase/token/refresh/{email}
     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     
     - parameter email: (path)  

     - returns: RequestBuilder<Void> 
     */
    open class func getTokenWithRequestBuilder(email: String) -> RequestBuilder<Void> {
        var path = "/v1/Firebase/token/refresh/{email}"
        let emailPreEscape = "\(email)"
        let emailPostEscape = emailPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{email}", with: emailPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
