//
// LocationsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class LocationsAPI {
    /**

     - parameter query: (query)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getAutocompleteAddress(query: String? = nil, completion: @escaping ((_ data: [GetAddressResponse]?,_ error: Error?) -> Void)) {
        getAutocompleteAddressWithRequestBuilder(query: query).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /v1/Locations/autocomplete/address
     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     - examples: [{contentType=application/json, example=[ {
  "country" : "country",
  "address" : "address",
  "latitude" : 0.8008281904610115,
  "suburb" : "suburb",
  "postCode" : "postCode",
  "state" : "NSW",
  "longitude" : 6.027456183070403
}, {
  "country" : "country",
  "address" : "address",
  "latitude" : 0.8008281904610115,
  "suburb" : "suburb",
  "postCode" : "postCode",
  "state" : "NSW",
  "longitude" : 6.027456183070403
} ]}]
     
     - parameter query: (query)  (optional)

     - returns: RequestBuilder<[GetAddressResponse]> 
     */
    open class func getAutocompleteAddressWithRequestBuilder(query: String? = nil) -> RequestBuilder<[GetAddressResponse]> {
        let path = "/v1/Locations/autocomplete/address"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "query": query
        ])

        let requestBuilder: RequestBuilder<[GetAddressResponse]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**

     - parameter query: (query)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getAutocompleteWorkAddress(query: String? = nil, completion: @escaping ((_ data: [GetEmployerPlaceResponse]?,_ error: Error?) -> Void)) {
        getAutocompleteWorkAddressWithRequestBuilder(query: query).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /v1/Locations/autocomplete/work
     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     - examples: [{contentType=application/json, example=[ {
  "country" : "country",
  "address" : "address",
  "latitude" : 0.8008281904610115,
  "name" : "name",
  "suburb" : "suburb",
  "postCode" : "postCode",
  "state" : "NSW",
  "longitude" : 6.027456183070403
}, {
  "country" : "country",
  "address" : "address",
  "latitude" : 0.8008281904610115,
  "name" : "name",
  "suburb" : "suburb",
  "postCode" : "postCode",
  "state" : "NSW",
  "longitude" : 6.027456183070403
} ]}]
     
     - parameter query: (query)  (optional)

     - returns: RequestBuilder<[GetEmployerPlaceResponse]> 
     */
    open class func getAutocompleteWorkAddressWithRequestBuilder(query: String? = nil) -> RequestBuilder<[GetEmployerPlaceResponse]> {
        let path = "/v1/Locations/autocomplete/work"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "query": query
        ])

        let requestBuilder: RequestBuilder<[GetEmployerPlaceResponse]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
