//
// LoggingAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class LoggingAPI {
    /**

     - parameter request: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func postLog(request: PostLogRequest? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        postLogWithRequestBuilder(request: request).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - POST /v1/Logging
     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     
     - parameter request: (body)  (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func postLogWithRequestBuilder(request: PostLogRequest? = nil) -> RequestBuilder<Void> {
        let path = "/v1/Logging"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: request)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**

     - parameter requests: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func postLogs(requests: [PostLogRequest]? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        postLogsWithRequestBuilder(requests: requests).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - POST /v1/Logging/list
     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     
     - parameter requests: (body)  (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func postLogsWithRequestBuilder(requests: [PostLogRequest]? = nil) -> RequestBuilder<Void> {
        let path = "/v1/Logging/list"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: requests)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

}
