//
// RecurringBillsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class RecurringBillsAPI {
    /**

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getRecurringBills(completion: @escaping ((_ data: [GetRecurringBillResponse]?,_ error: Error?) -> Void)) {
        getRecurringBillsWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /v1/RecurringBills
     - API Key:
       - type: apiKey Authorization 
       - name: Bearer
     - examples: [{contentType=application/json, example=[ {
  "amount" : 6.027456183070403,
  "recurringFrequency" : "Weekly",
  "endDate" : "endDate",
  "isAddedByUser" : true,
  "description" : "description",
  "merchant" : "merchant",
  "id" : 0,
  "merchantLogoUrl" : "merchantLogoUrl",
  "startDate" : "startDate"
}, {
  "amount" : 6.027456183070403,
  "recurringFrequency" : "Weekly",
  "endDate" : "endDate",
  "isAddedByUser" : true,
  "description" : "description",
  "merchant" : "merchant",
  "id" : 0,
  "merchantLogoUrl" : "merchantLogoUrl",
  "startDate" : "startDate"
} ]}]

     - returns: RequestBuilder<[GetRecurringBillResponse]> 
     */
    open class func getRecurringBillsWithRequestBuilder() -> RequestBuilder<[GetRecurringBillResponse]> {
        let path = "/v1/RecurringBills"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<[GetRecurringBillResponse]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
